# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: speecht-to-text-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speecht-to-text-app
  template:
    metadata:
      labels:
        app: speecht-to-text-app
    spec:
      containers:
      - name: speecht-to-text-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/coding-api-challange/helloworld-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"