apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: speech-to-text-app
  labels:
    name: speech-to-text-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: speech-to-text-app
  template:
    metadata:
      name: speech-to-text-app
      labels:
        name: speech-to-text-app
    spec:
      containers:
        - name: speech-to-text-app
          image: gcr.io/coding-api-challange/flask-app:v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"